export const GET_VIDEOGAMES = "GET_VIDEOGAMES";
export const GET_VIDEOGAME = "GET_VIDEOGAME";
export const SEARCH_BY_NAME = 'SEARCH_BY_NAME';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';